version: '3'

services:
  php:
    image: php:7.4-apache
    container_name: app_delivery
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - /home/mw/Documentos/Cursos/Programacao/hugo_vasconcelos/Sistema_delivere/app/site:/var/www/html
    links:
      - db

  db:
    image: mysql:latest
    container_name: db_delivery
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root