version: "3"

services:
  apache:
    image: 'php:7.4-apache'
    container_name: app_delivery
    restart: always
    ports:
      - '8080:80'
      - "443:443"
    volumes:
    - /home/mw/Documentos/Cursos/Programacao/hugo_vasconcelos/Sistema_delivere/app/site:/var/www/html